# Generated by Django 5.2.1 on 2025-05-18 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('car_type', models.CharField(choices=[('XL', 'SUV'), ('SE', 'SEDAN'), ('MINI', 'HATCHBACK'), ('CO', 'COUPE'), ('CONV', 'CONVERTIBLE')], max_length=4)),
            ],
        ),
    ]
